// Define types for test data

export interface Todo {
  id?: string;  // Optional since it's generated by the database on insert
  title: string;
  description: string;
  status: string;
  created_by: string;
  created_at?: string;
  updated_at?: string;
}

// Type for creating a new Todo
export interface CreateTodo {
  title: string;
  description: string;
  status: string;
  created_by: string;
}