name: E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build the app
        run: npm run build

      - name: Start the app in background
        run: npm run preview &
        env:
          PUBLIC_SITE_URL: http://localhost:4321
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Wait for app to start
        run: npx wait-on http://localhost:4321 -t 60000

      # Run only the mock tests in CI by default (since they don't need real API keys)
      - name: Run Playwright E2E Tests with mocking
        run: npx playwright test e2e/flashcard-generation-mock.spec.ts
        env:
          CI: true

      # Skip real API tests if OpenRouter key is not available
      - name: Run Full E2E Tests (if API key available)
        if: ${{ env.OPENROUTER_API_KEY != '' }}
        run: npx playwright test e2e/flashcard-generation.spec.ts
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 14