name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PUBLIC_SITE_URL: ${{ secrets.PUBLIC_SITE_URL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format -- --check

      - name: Run unit & integration tests
        run: npm run test

      - name: Upload unit test coverage
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 7

      - name: Install Playwright Browsers
        # Only install Chromium browser as per the playwright config
        run: npx playwright install chromium

      - name: Run E2E Tests
        run: npm run e2e
        env:
          CI: true
          BASE_URL: ${{ secrets.PUBLIC_SITE_URL || 'http://localhost:3000' }}
          PLAYWRIGHT_TIMEOUT: 60000

      - name: Upload E2E Test Results
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7